pipeline {
  agent {
     node { 
        label 'node01'
     } 
  }
  tools {
    maven 'maven-apache-3.8.4'
  }
  stages {
    stage('Maven Package') {
      steps {
        sh 'mvn package'
      }
    }
    stage('Run') {
      steps {
        sh 'java -jar target/my-app-1.0-SNAPSHOT.jar'
      }
    }
  }
  post {
    always {
      step($class: 'JUnitResultArchiver', checksName: '', testResults: '**/surefire-reports/TEST-*.xml')
      step(followSymlinks: false, $class: 'ArtifactArchiver', artifacts: 'target/*.jar')
    }
  }
}
